
#build only for unstable branch
branches:
   only:
     - unstable

language: objective-c

#before the script is run for the build, inject data into test_credentials file
before_script:
   - ./build/pre-build

script:
   #build all schemes
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCommon
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSecurity
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceOAuth
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCore
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceNetworkiOS
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceRestAPI
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSync
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceHybridSDK
   # run all tests
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCommon -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSecurity -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceOAuthTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCoreUnitTestApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceNetworkiOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSync -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceHybridSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme OCMockLib -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme HybridPluginTestApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceNetworkiOSTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
