#build only for unstable branch
branches:
   only:
     - unstable

language: objective-c
osx_image: xcode7.2

env:
  matrix:
    - SDK=iphonesimulator OS=8.4 NAME="iPhone 6"
    - SDK=iphonesimulator9.2 OS=9.2 NAME="iPhone 6"
    - SDK=iphonesimulator OS=8.4 NAME="iPad 2"
    - SDK=iphonesimulator9.2 OS=9.2 NAME="iPad 2"

before_install:
   - gem install xcpretty

#before the script is run for the build, inject data into test_credentials file
before_script:
   - ./build/pre-build

script:
   # build libs
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCore CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceNetwork CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceRestAPI CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SmartStore CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSync CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceHybridSDK CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceReact CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   # build native sample apps
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme RestAPIExplorer CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSyncExplorer CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   # build hybrid sample apps
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme AccountEditor CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme NoteSync CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   - set -o pipefail && xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSyncExplorerHybrid CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
   # run tests that don't need a host app
   - set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceNetworkTests -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   - set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceHybridSDKTests -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   - set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCoreTests -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   - set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SmartStoreTests -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   - set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSyncTests -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   - set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceRestAPITests -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   # run tests that need a host app
   # set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCoreTestApp -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   # set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceRestAPITestApp -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   # set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SmartStoreTestApp -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   # set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSyncTestApp -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"
   # set -o pipefail && xctool test -parallelize -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceHybridSDKTestApp -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"