branches:
   only:
     - unstable

language: objective-c

before_script:
   - ./build/pre-build

script:
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCommon
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSecurity
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceOAuth
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCore
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceNetworkiOS
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceRestAPI
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSync
   - xctool -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceHybridSDK

   - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCommon -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
