
#build only for unstable branch
branches:
   only:
     - unstable

language: objective-c

before_install:
   - gem install xcpretty

#before the script is run for the build, inject data into test_credentials file
before_script:
   - ./build/pre-build

script:
   #build all schemes
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme AccountEditor | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme NoteSync | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme OCMock | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme OCMockLib | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme React | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme RestAPIExplorer | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceHybridSDK | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceNetworkiOS | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceOAuth | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceReact | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceRestAPI | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCommon | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCore | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSecurity | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SimpleSync | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSync | xcpretty --color --simple
   - xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSyncExplorer | xcpretty --color --simple
   # run all tests
   - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCommon -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSecurity -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceOAuthTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCoreUnitTestApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceNetworkiOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   # - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceRestAPIUnitTestApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSync -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceHybridSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme OCMockLib -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   # - xctool test -workspace SalesforceMobileSDK.xcworkspace -scheme HybridPluginTestApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
   - xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceNetworkiOSTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty --color --simple --test
